export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST'
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS'
export const ADMIN_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL'
export const ADMIN_SIGNOUT = 'ADMIN_SIGNOUT'

export const ADMIN_SIGNUP_REQUEST = 'ADMIN_SIGNUP_REQUEST'
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS'
export const ADMIN_SIGNUP_FAIL = 'ADMIN_SIGNUP_FAIL'

export const GET_STOCK_REQUEST = 'GET_STOCK_REQUEST'
export const GET_STOCK_SUCCESS = 'GET_STOCK_SUCCESS'
export const GET_STOCK_FAIL = 'GET_STOCK_FAIL'

export const GET_SUPPLIER_REQUEST = 'GET_SUPPLIER_REQUEST'
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS'
export const GET_SUPPLIER_FAIL = 'GET_SUPPLIER_FAIL'

export const GET_INGREDIENT_REQUEST = 'GET_INGREDIENT_REQUEST'
export const GET_INGREDIENT_SUCCESS = 'GET_INGREDIENT_SUCCESS'
export const GET_INGREDIENT_FAIL = 'GET_INGREDIENT_FAIL'

export const GET_MENU_REQUEST = 'GET_MENU_REQUEST'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_FAIL = 'GET_MENU_FAIL'

export const ADD_MENU_REQUEST = 'ADD_MENU_REQUEST'
export const ADD_MENU_SUCCESS = 'ADD_MENU_SUCCESS'
export const ADD_MENU_FAIL = 'ADD_MENU_FAIL'
export const RESET_ADD_MENU = 'RESET_ADD_MENU'

export const UPDATE_STOCK_REQUEST = 'UPDATE_STOCK_REQUEST'
export const UPDATE_STOCK_SUCCESS = 'UPDATE_STOCK_SUCCESS'
export const UPDATE_STOCK_FAIL = 'UPDATE_STOCK_FAIL'
export const RESET_UPDATE_STOCK = 'RESET_UPDATE_STOCK'

export const GET_FEEDBACK_REQUEST = 'GET_FEEDBACK_REQUEST'
export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS'
export const GET_FEEDBACK_FAIL = 'GET_FEEDBACK_FAIL'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const UPDATE_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'GET_PROFILE_FAIL'
export const RESET_UPDATE_PROFILE = 'RESET_UPDATE_PROFILE'

