export const GET_APPROVEDORDERS_REQUEST = 'GET_APPROVEDORDERS_REQUEST'
export const GET_APPROVEDORDERS_SUCCESS = 'GET_APPROVEDORDERS_SUCCESS'
export const GET_APPROVEDORDERS_FAIL = 'GET_APPROVEDORDERS_FAIL'

export const POST_PREPAREORDER_REQUEST = 'POST_PREPAREORDER_REQUEST'
export const POST_PREPAREORDER_SUCCESS = 'POST_PREPAREORDER_SUCCESS'
export const POST_PREPAREORDER_FAIL = 'POST_PREPAREORDER_FAIL'
