export const CUSTOMER_SIGNIN_REQUEST = 'CUSTOMER_SIGNIN_REQUEST'
export const CUSTOMER_SIGNIN_SUCCESS = 'CUSTOMER_SIGNIN_SUCCESS'
export const CUSTOMER_SIGNIN_FAIL = 'CUSTOMER_SIGNIN_FAIL'
export const CUSTOMER_SIGNOUT = 'CUSTOMER_SIGNOUT'

export const CUSTOMER_SIGNUP_REQUEST = 'CUSTOMER_SIGNUP_REQUEST'
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS'
export const CUSTOMER_SIGNUP_FAIL = 'CUSTOMER_SIGNUP_FAIL'

export const CUSTOMER_GETCART_REQUEST = 'CUSTOMER_GETCART_REQUEST'
export const CUSTOMER_GETCART_SUCCESS = 'CUSTOMER_GETCART_SUCCESS'
export const CUSTOMER_GETCART_FAIL = 'CUSTOMER_GETCART_FAIL'

export const CUSTOMER_CARTUPDATE_REQUEST = 'CUSTOMER_CART_UDATE'
export const CUSTOMER_CARTUPDATE_SUCCESS = 'CUSTOMER_CARTUPDATE_SUCCESS'
export const CUSTOMER_CARTUPDATE_FAIL = 'CUSTOMER_CARTUPDATE_FAIL'

export const CUSTOMER_PLACEORDER_REQUEST = 'CUSTOMER_PLACEORDER_REQUEST'
export const CUSTOMER_PLACEORDER_SUCCESS = 'CUSTOMER_PLACEORDER_SUCCESS'
export const CUSTOMER_PLACEORDER_FAIL = 'CUSTOMER_PLACEORDER_FAIL'

export const CUSTOMER_ADDTOCART_REQUEST = 'CUSTOMER_ADDTOCART_REQUEST'
export const CUSTOMER_ADDTOCART_SUCCESS = 'CUSTOMER_ADDTOCART_SUCCESS'
export const CUSTOMER_ADDTOCART_FAIL = 'CUSTOMER_ADDTOCART_FAIL'

export const CUSTOMER_BOOKTABLE_REQUEST = 'CUSTOMER_BOOKTABLE_REQUEST'
export const CUSTOMER_BOOKTABLE_SUCCESS = 'CUSTOMER_BOOKTABLE_SUCCESS'
export const CUSTOMER_BOOKTABLE_FAIL = 'CUSTOMER_BOOKTABLE_FAIL'

export const CUSTOMER_GETORDERS_REQUEST = 'CUSTOMER_BOOKTABLE_REQUEST'
export const CUSTOMER_GETORDERS_SUCCESS = 'CUSTOMER_BOOKTABLE_SUCCESS'
export const CUSTOMER_GETORDERS_FAIL = 'CUSTOMER_BOOKTABLE_FAIL'

export const CUSTOMER_FEEDBACK_REQUEST = 'CUSTOMER_FEEDBACK_REQUEST'
export const CUSTOMER_FEEDBACK_SUCCESS = 'CUSTOMER_FEEDBACK_SUCCESS'
export const CUSTOMER_FEEDBACK_FAIL = 'CUSTOMER_FEEDBACK_FAIL'
export const CUSTOMER_FEEDBACK_RESET = 'CUSTOMER_FEEDBACK_RESET'

export const CUSTOMER_PAYBILL_REQUEST = 'CUSTOMER_PAYBILL_REQUEST'
export const CUSTOMER_PAYBILL_SUCCESS = 'CUSTOMER_PAYBILL_SUCCESS'
export const CUSTOMER_PAYBILL_FAIL = 'CUSTOMER_PAYBILL_FAIL'
export const CUSTOMER_PAYBILL_RESET = 'CUSTOMER_PAYBILL_RESET'
