export const MANAGER_GETORDERS_REQUEST = 'MANAGER_GETORDERS_REQUEST'
export const MANAGER_GETORDERS_SUCCESS = 'MANAGER_GETORDERS_SUCCESS'
export const MANAGER_GETORDERS_FAIL = 'MANAGER_GETORDERS_FAIL'
export const MANAGER_GETORDERS_RESET = 'MANAGER_GETORDERS_RESET'

export const GET_CHEFS_REQUEST = 'GET_CHEFS_REQUEST'
export const GET_CHEFS_SUCCESS = 'GET_CHEFS_SUCCESS'
export const GET_CHEFS_FAIL = 'GET_CHEFS_FAIL'
export const GET_CHEFS_RESET = 'GET_CHEFS_RESET'

export const MANAGER_APPROVEORDER_REQUEST = 'MANAGER_APPROVEORDER_REQUEST'
export const MANAGER_APPROVEORDER_SUCCESS = 'MANAGER_APPROVEORDER_SUCCESS'
export const MANAGER_APPROVEORDER_FAIL = 'MANAGER_APPROVEORDER_FAIL'
export const MANAGER_APPROVEORDER_RESET = 'MANAGER_APPROVEORDER_RESET'

export const GET_WAITERS_REQUEST = 'GET_WAITERS_REQUEST'
export const GET_WAITERS_SUCCESS = 'GET_WAITERS_SUCCESS'
export const GET_WAITERS_FAIL = 'GET_WAITERS_FAIL'
export const GET_WAITERS_RESET = 'GET_WAITERS_RESET'

export const ASSIGN_WAITER_REQUEST = 'ASSIGN_WAITER_REQUEST'
export const ASSIGN_WAITER_SUCCESS = 'ASSIGN_WAITER_SUCCESS'
export const ASSIGN_WAITER_FAIL = 'ASSIGN_WAITER_FAIL'
export const ASSIGN_WAITER_RESET = 'ASSIGN_WAITER_RESET'
