export const GET_ALLWEEKREVENUE_REQUEST = 'GET_ALLWEEKREVENUE_REQUEST'
export const GET_ALLWEEKREVENUE_SUCCESS = 'GET_ALLWEEKREVENUE_SUCCESS'
export const GET_ALLWEEKREVENUE_FAIL = 'GET_ALLWEEKREVENUE_FAIL'

export const GET_ALLMONTHREVENUE_REQUEST = 'GET_ALLMONTHREVENUE_REQUEST'
export const GET_ALLMONTHREVENUE_SUCCESS = 'GET_ALLMONTHREVENUE_SUCCESS'
export const GET_ALLMONTHREVENUE_FAIL = 'GET_ALLMONTHREVENUE_FAIL'

export const GET_TODAYSREVENUE_REQUEST = ' GET_TODAYSREVENUE_REQUEST'
export const GET_TODAYSREVENUE_SUCCESS = 'GET_TODAYSREVENUE_SUCCESS'
export const GET_TODAYSREVENUE_FAIL = 'GET_TODAYSREVENUE_FAIL'

export const GET_THISWEEKREVENUE_REQUEST = 'GET_THISWEEKREVENUE_REQUEST'
export const GET_THISWEEKREVENUE_SUCCESS = 'GET_THISWEEKREVENUE_SUCCESS'
export const GET_THISWEEKREVENUE_FAIL = 'GET_THISWEEKREVENUE_FAIL'

export const GET_THISMONTHSREVENUE_REQUEST = 'GET_THISMONTHSREVENUE_REQUEST'
export const GET_THISMONTHSREVENUE_SUCCESS = 'GET_THISMONTHSREVENUE_SUCCESS'
export const GET_THISMONTHSREVENUE_FAIL = 'GET_THISMONTHSREVENUE_FAIL'

export const GET_THISYEARSREVENUE_REQUEST = 'GET_THISYEARSREVENUE_REQUEST'
export const GET_THISYEARSREVENUE_SUCCESS = 'GET_THISYEARSREVENUE_SUCCESS'
export const GET_THISYEARSREVENUE_FAIL = 'GET_THISYEARSREVENUE_FAIL'
