export const GET_PREPAREDORDERS_REQUEST = 'GET_PREPAREDORDERS_REQUEST'
export const GET_PREPAREDORDERS_SUCCESS = 'GET_PREPAREDORDERS_SUCCESS'
export const GET_PREPAREDORDERS_FAIL = 'GET_PREPAREDORDERS_FAIL'

export const POST_SERVEORDER_REQUEST = 'POST_SERVEORDER_REQUEST'
export const POST_SERVEORDER_SUCCESS = 'POST_SERVEORDER_SUCCESS'
export const POST_SERVEORDER_FAIL = 'POST_SERVEORDER_FAIL'
