export const GET_INGREDIENT_REQUEST = 'GET_INGREDIENT_REQUEST'
export const GET_INGREDIENT_SUCCESS = 'GET_INGREDIENT_SUCCESS'
export const GET_INGREDIENT_FAIL = 'GET_INGREDIENT_FAIL'
export const RESET_INGREDIENT_STATE = 'RESET_INGREDIENT_STATE'

export const UPDATE_INGREDIENT_REQUEST = 'UPDATE_INGREDIENT_REQUEST'
export const UPDATE_INGREDIENT_SUCCESS = 'UPDATE_INGREDIENT_SUCCESS'
export const UPDATE_INGREDIENT_FAIL = 'UPDATE_INGREDIENT_FAIL'
export const RESET_UPDATE_INGREDIENT_STATE = 'RESET_UPDATE_INGREDIENT_STATE'

export const ADD_INGREDIENT_REQUEST = 'ADD_INGREDIENT_REQUEST'
export const ADD_INGREDIENT_SUCCESS = 'ADD_INGREDIENT_SUCCESS'
export const ADD_INGREDIENT_FAIL = 'ADD_INGREDIENT_FAIL'
export const RESET_ADD_INGREDIENT_STATE = 'RESET_ADD_INGREDIENT_STATE'
